name: Deploy to Staging

on:
  push:
    branches: ["staging"]

jobs:
  deploy-render:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to staging environment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
